sudo: required
language: python

services:
  - docker



before_script:
  - docker-compose up -d --build

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "zadanie1"
  env: "zadanie1-env"
  bucket_name: "elasticbeanstalk-eu-central-1-983021526080"
  bucket_path: "zadanie1"
  edge: true
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  
