version: '3.9'

services:
  web:
      build: .
      command: sh -c "python3 manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/code
      ports:
        - "30:8000"
